Fix build when CC contains parameters
The error message is as follows:
```
running build_ext
"cc -pthread" -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -c imio.c -o imio.o
error: command 'cc -pthread' failed: No such file or directory

ERROR Backend subprocess exited when trying to invoke build_wheel
*** Error code 1
```